github:
  description: "Apache XML Graphics FOP"
  homepage: https://xmlgraphics.apache.org/fop/
  labels:
    - fop
    - apache

notifications:
  commits:      commits@xmlgraphics.apache.org
  # issues:       fop-dev@xmlgraphics.apache.org
  # pullrequests: fop-dev@xmlgraphics.apache.org
  # jobs: fop-dev@xmlgraphics.apache.org
  jira_options: link label
